apiVersion: apps/v1
kind: Deployment
metadata:
  name: Odoo_web
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:13.0
        ports:
        - containerPort: 8069