apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-web
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - image: odoo:13.0
        name: odoo
        securityContext:
         runAsUser: 0
         runAsGroup: 0
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: bdd-clusterip
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
        volumeMounts:
        - name: odoo-volume
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-volume
        hostPath:
          path: /odoo-data
          type: DirectoryOrCreate
        