apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-web
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - image: odoo:13.0
        name: odoo
        ports:
        - containerPort: 8069
        volumeMounts:
        - mountPath: /var/lib/odoo
          name: odoo-volume
      volumes:
      - name: odoo-volume
        hostPath:
            path: /odoo-data
            type: DirectoryOrCreate
        