version: '3.1'
services:
  odoo:
    image: odoo:13.0
    container_name: Odoo_Web
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - odoo-data:/var/lib/odoo
    networks:
      - ic_network

  db:
    image: postgres
    container_name: BDD_Odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ic_network

volumes:
  odoo-data:
  db-data:
networks:
  ic_network:
    driver: bridge