version: '3.1'
services:
  ic:
      image: mozkadocker/ic-webapp:1.0
      container_name: Ic-webapp
      depends_on:
        - pg
        - db
      environment:
        - ODOO_URL=http://192.168.56.10:8080
        - PGADMIN_URL=http://192.168.56.10:5050
      ports:
        - "80:8080"
      networks:
        - ic_network
  pg:
      image: dpage/pgadmin4
      container_name: Pgadmin
      ports:
        - "5050:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL=mozkatraining@eazy.fr
        - PGADMIN_DEFAULT_PASSWORD=password
      volumes:
        - ${PWD}/servers.json:/pgadmin4/servers.json
        - pgadmin-data:/var/lib/pgadmin
      networks:
        - ic_network

volumes:
  pgadmin-data:
networks:
  ic_network:
    driver: bridge
