apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ic-webapp-pod
  template:
    metadata:
      name: ic-webapp-template
      labels:
        app: ic-webapp-pod
    spec:
      containers:
      - image: mozkadocker/ic-webapp:1.0
        name: ic-webapp
        env:
        - name: ODOO_URL
          value: http://192.168.56.10:30002
        - name: PGADMIN_URL
          value: http://192.168.56.10:30003
        ports:
        - containerPort: 8080