version: '3.1'
services:
  pg:
      image: dpage/pgadmin4
      container_name: Pgadmin
      ports:
        - "5050:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL=mozkatraining@eazy.fr
        - PGADMIN_DEFAULT_PASSWORD=password
      volumes:
        - ${PWD}/pgadmin4/servers.json:/pgadmin4/servers.json
        - pgadmin-data:/var/lib/pgadmin
      networks:
        - ic_network

volumes:
  pgadmin-data:
networks:
  ic_network:
    driver: bridge